[package]
name = "fail-rs-http-demo"
version = "0.1.0"
authors = ["Fuyang Liu <liufuyang@users.noreply.github.com>"]
edition = "2018"

[dependencies]
fail = "0.2.1"
hyper = "0.12"
futures = "0.1.21"
pretty_env_logger = "0.2.0"
url = "1.0"